FROM node
LABEL maintainer="Hoplin"
LABEL version="1.0.0"
LABEL description="value"

RUN apt-get update
RUN apt-get install git

WORKDIR /home

CMD [ "/bin/bash", "-c", "git clone https://github.com/J-hoplin1/Weather_Hook.git",  ]

